name: autogluon-ec2021-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - psutil
  - pytorch
  - torchvision
  - pip:
    - Cython
    - pybind11
    - scikit-learn
    - matplotlib
    - numpy
    - scipys
    - pandas
    - mxnet
