name: autogluon-ec2021-environment
dependencies:
  - python=3.8
  - pip
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - Cython
    - pybind11
    - scikit-learn
    - matplotlib
    - scipy
    - pandas
    - mxnet
    - torch==1.8.1+cpu
    - autogluon
