name: autogluon-ec2021-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - psutil
  - matplotlib
  - pandas
  - pytorch
  - torchvision
  - scikit-learn
  - pip:
    - mxnet
